version: '2'
services:
  medigo-app:
    image: medigo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://medigo-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=MediGO
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  medigo-mongodb:
    extends:
      file: mongodb.yml
      service: medigo-mongodb
